prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>

select ?branch (count(distinct ?child_class) as ?class_count)
 where {
    ?branch rdfs:subClassOf owl:Thing .
    ?child_class rdfs:subClassOf* ?branch .
}
group by ?branch
order by ?branch


