prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix oio: <http://www.geneontology.org/formats/oboInOwl#>

select distinct ?branch ?child_class ?is_a_edge
 where {
    values ?syn_type {
        oio:hasExactSynonym
        oio:hasRelatedSynonym
    }
    ?branch rdfs:subClassOf owl:Thing .
    ?child_class rdfs:subClassOf* ?branch .
    ?child_class rdfs:subClassOf ?is_a_edge .
    minus {
        ?child_class rdfs:subClassOf owl:Thing .
    }
    filter(isiri(?is_a_edge))
}
order by ?branch ?child_class ?is_a_edge


