---
name: New Term Request
description: Use this template for requesting a new term.
title: "[NEW TERM]"
labels: [enhancement]
body:
    - type: markdown
      attributes:
          value: For new term requests, please provide the following information.
    - type: input
      id: term_label
      attributes:
          label: Preferred Term Label
          description: What should the label of the new term be? Or, if it already exists, what is its label?
          placeholder: NamedThing
      validations:
          required: true
    - type: input
      id: term_synonyms
      attributes:
          label: Preferred Synonyms
          description: Should there be any synoyms for this term, whether it already exists or is being proposed?
    - type: input
      id: textual_definition
      attributes:
          label: Textual Definition
          description: What should the definition of this term be? The definition should be understandable even for non-specialists.
    - type: input
      id: reference
      attributes:
          label: Reference
          description: Please provide a source for the existence of this term as a URL or DOI.
    - type: input
      id: suggested_parent_term
      attributes:
          label: Suggested Parent Term
          description: Please provide a potential parent term if you are suggesting creation of a new term.
    - type: input
      id: contributor_orcid
      attributes:
          label: Curator
          description: If you would like a nanoattribution, please probvide your ORCID id.
          placeholder: 0000-0001-2345-6789
